
-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies

-- drop Views and dependencies

-- drop Types and dependencies

-- alter database structure

-- [ENHANCEMENT] Speed up Upload/Delete process #95
ALTER TABLE TM_DATA_CELL

DROP CONSTRAINT FK_TM_DATA_CELL_TD_MATRIX;

ALTER TABLE TM_DATA_CELL

DROP CONSTRAINT FK_TM_DATA_CELL_TD_VARIABLE;

ALTER TABLE TD_DATA

DROP CONSTRAINT FK_TD_DATA_TD_MATRIX;

ALTER TABLE TD_DATA

DROP CONSTRAINT FK_TD_DATA_TD_PERIOD;

ALTER TABLE TD_DATA

DROP CONSTRAINT FK_TD_DATA_TD_STATISTIC;

ALTER TABLE TD_PERIOD

DROP CONSTRAINT FK_TD_PERIOD_TD_FREQUENCY;

ALTER TABLE TD_VARIABLE

DROP CONSTRAINT FK_TD_VARIABLE_TD_CLASSIFICATION;


-- alter database data