
-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies


-- drop Views and dependencies

-- drop Types and dependencies

-- alter database structure

	-- [ENHANCEMENT] Create new entity and API for monitoring server performance #254
	CREATE TABLE [dbo].[TD_PERFORMANCE](
		[PRF_ID] [bigint] IDENTITY(1,1) NOT NULL,
		[PRF_PROCESSOR_PERCENTAGE] [tinyint] NOT NULL,
		[PRF_MEMORY_AVAILABLE] [int] NOT NULL,
		[PRF_REQUEST_QUEUE] [smallint] NOT NULL,
		[PRF_REQUEST_PERSECOND] [smallint] NOT NULL,
		[PRF_DATETIME] [datetime] NOT NULL,
		[PRF_SERVER] [nvarchar](256) NOT NULL,
	 CONSTRAINT [PK_TD_PERFORMANCE] PRIMARY KEY CLUSTERED 
	(
		[PRF_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO
	CREATE NONCLUSTERED INDEX [IX_PRF_DATETIME] ON [dbo].[TD_PERFORMANCE]
	(
		[PRF_DATETIME] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO
	CREATE NONCLUSTERED INDEX [IX_PRF_SERVER] ON [dbo].[TD_PERFORMANCE]
	(
		[PRF_SERVER] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO
	
	-- [ENHANCEMENT] Create new entity and API for monitoring server performance #254
	GRANT ALTER ON OBJECT::[dbo].[TD_PERFORMANCE] TO [pxstat]
	GO
	CREATE
	OR

	ALTER VIEW [dbo].[VW_PERFORMANCE_AVERAGES]
	AS
	SELECT PRF_SERVER
	,PRF_DATETIME
	,AVG(PRF_PROCESSOR_PERCENTAGE) AS 'AVG_PROCESSOR_PERCENTAGE'
	,AVG(PRF_MEMORY_AVAILABLE) AS 'AVG_MEMORY_AVAILABLE'
	,AVG(PRF_REQUEST_QUEUE) AS 'AVG_REQUEST_QUEUE'
	,AVG(PRF_REQUEST_PERSECOND) AS 'AVG_REQUEST_PERSECOND'
	FROM TD_PERFORMANCE
	GROUP BY PRF_SERVER
	,PRF_DATETIME
	GO
	
    -- [BUG] Update WIP properties if live release gets updated #276
	ALTER TABLE TD_WORKFLOW_REQUEST
	ADD WRQ_EXPERIMENTAL_FLAG BIT NULL DEFAULT(0)

	CREATE NONCLUSTERED INDEX [IX_WRQ_EXPERIMENTAL_FLAG] ON [dbo].[TD_WORKFLOW_REQUEST]
	(
		[WRQ_EXPERIMENTAL_FLAG] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO

		ALTER TABLE TD_RELEASE
		ADD RLS_EXPERIMENTAL_FLAG BIT NOT NULL DEFAULT(0)

		CREATE NONCLUSTERED INDEX [IX_RLS_EXPERIMENTAL_FLAG] ON [dbo].[TD_RELEASE]
	(
		[RLS_EXPERIMENTAL_FLAG] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO
	
	-- [ENHANCEMENT] Include workflow request details in comparison modal #277
	DROP INDEX [IX_WRQ_ALERT_FLAG] ON [dbo].[TD_WORKFLOW_REQUEST]
	GO

	ALTER TABLE TD_WORKFLOW_REQUEST
	DROP COLUMN WRQ_ALERT_FLAG
	
-- alter database data 

	-- [BUG] Backward compatible JSON-stat outputs need to be based on version 1.0, not on 1.1 #259 
	UPDATE TS_FORMAT
	SET FRM_VERSION='1.0'
	WHERE FRM_TYPE='JSON-stat'
	AND FRM_VERSION='1.1'
	AND FRM_DIRECTION='DOWNLOAD'

