
-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies

-- drop Views and dependencies

-- drop Types and dependencies

-- alter database structure
	
	-- [ENHANCEMENT] Open access changes #324
	CREATE TABLE TD_LOGIN (
		LGN_ID int IDENTITY(1,1)  not null,
		LGN_1FA varchar(64) NULL,
		LGN_2FA nvarchar(max) NULL,
		LGN_TOKEN_1FA varchar(64) NULL,
		LGN_TOKEN_2FA varchar(64) NULL,
		LGN_SESSION varchar(64) NULL,
		LGN_SESSION_EXPIRY DATETIME NULL,
		LGN_CCN_ID INT NOT NULL
	 CONSTRAINT PK_TD_LOGIN PRIMARY KEY CLUSTERED 
	(
		LGN_ID ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
	GO

	CREATE NONCLUSTERED INDEX IX_LGN_SESSION ON TD_LOGIN
	(
		LGN_SESSION ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO

	CREATE NONCLUSTERED INDEX [IX_LGN_TOKEN_1FA] ON [dbo].[TD_LOGIN]
	(
		[LGN_TOKEN_1FA] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO

	CREATE NONCLUSTERED INDEX [IX_LGN_TOKEN_2FA] ON [dbo].[TD_LOGIN]
	(
		[LGN_TOKEN_2FA] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO

	ALTER TABLE [dbo].[TD_LOGIN]  WITH CHECK ADD  CONSTRAINT [FK_TD_LOGIN_TD_ACCOUNT] FOREIGN KEY([LGN_CCN_ID])
	REFERENCES [dbo].[TD_ACCOUNT] ([CCN_ID])
	GO

	ALTER TABLE TD_ACCOUNT
	ADD CCN_DISPLAYNAME NVARCHAR(256) NULL
	go

	ALTER TABLE TD_ACCOUNT
	ADD CCN_EMAIL NVARCHAR(256) NULL
	go

	ALTER TABLE TD_ACCOUNT
	ADD CCN_LOCKED_FLAG BIT NOT NULL DEFAULT(0)
	GO

	ALTER TABLE TD_ACCOUNT
	ADD CCN_AD_FLAG BIT NOT NULL DEFAULT(0)
	GO
	
	CREATE NONCLUSTERED INDEX IX_CCN_EMAIL ON dbo.TD_ACCOUNT
	(
		CCN_EMAIL ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO

	CREATE NONCLUSTERED INDEX IX_CCN_LOCKED_FLAG ON dbo.TD_ACCOUNT
	(
		CCN_LOCKED_FLAG ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO

	CREATE NONCLUSTERED INDEX IX_CCN_AD_FLAG ON dbo.TD_ACCOUNT
	(
		CCN_AD_FLAG ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	GO
	
	
-- alter database data 


	-- [ENHANCEMENT] Open access changes #324
	UPDATE TD_ACCOUNT 
	SET CCN_AD_FLAG=1
	GO
	
	INSERT INTO TD_LOGIN (LGN_CCN_ID)
	SELECT CCN_ID
	FROM TD_ACCOUNT
	WHERE CCN_DELETE_FLAG = 0
		AND CCN_ID NOT IN (
			SELECT LGN_CCN_ID
			FROM TD_LOGIN
			)
	GO
	
	-- [BUG] HTML tags not being removed from px file on import #368
	UPDATE TD_MATRIX
	SET MTR_NOTE=REPLACE((REPLACE(MTR_NOTE,'<i>','[i]')),'</i>','[/i]') 

	UPDATE TD_MATRIX
	set MTR_NOTE=REPLACE((REPLACE(MTR_NOTE,'<b>','[b]')),'</b>','[/b]')

	UPDATE TD_MATRIX 
	SET MTR_NOTE=REPLACE((REPLACE(MTR_NOTE,'<u>','[u]')),'</u>','[/u]')

	UPDATE TD_MATRIX 
	SET MTR_NOTE=REPLACE((REPLACE(MTR_NOTE,'<a href','[url')),'</a>','[/url]')

	UPDATE TD_MATRIX 
	SET MTR_NOTE=REPLACE((REPLACE((REPLACE(MTR_NOTE,'<br>','\n')),'<br/>','\n')),'<br />','\n')

	UPDATE TD_MATRIX 
	SET MTR_NOTE=REPLACE((REPLACE(MTR_NOTE,'<','[')),'>',']')

