

-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies

-- drop Views and dependencies

-- drop Types and dependencies

-- alter database structure
ALTER DATABASE CURRENT SET ARITHABORT ON 
GO

DROP INDEX IX_TDT_OPTIMISER ON [dbo].[TD_DATA]
GO

DROP INDEX IX_DTC_OPTIMISER ON [dbo].[TM_DATA_CELL]
GO

CREATE NONCLUSTERED INDEX [IX_TDT_OPTIMISER] ON [dbo].[TD_DATA]
(
	[TDT_IX] ASC,
	[TDT_MTR_ID] ASC,
	[TDT_STT_ID] ASC,
	[TDT_PRD_ID] ASC
)
INCLUDE([TDT_ID],[TDT_VALUE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_DTC_OPTIMISER] ON [dbo].[TM_DATA_CELL]
(
	[DTC_MTR_ID] ASC,
	[DTC_VRB_ID] ASC,
	[DTC_TDT_IX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER DATABASE CURRENT 
SET AUTO_UPDATE_STATISTICS_ASYNC ON