

-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies

-- drop Views and dependencies

-- drop Types and dependencies

-- alter Tables, Sequences, Defaults

CREATE TABLE [dbo].[TD_THEME](
	[THM_ID] [int] IDENTITY(1,1) NOT NULL,
	[THM_CODE] [int] NOT NULL,
	[THM_VALUE] [nvarchar](256) NOT NULL,
	[THM_LNG_ID][int] NOT NULL,
	[THM_DTG_ID] [int] NOT NULL,
	[THM_DELETE_FLAG] [bit] NOT NULL
 CONSTRAINT [PK_TD_THEME] PRIMARY KEY CLUSTERED 
(
	[THM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE SEQUENCE [dbo].[THM_CODE_seq] 
 AS [int]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 2147483647
 CACHE 
GO
ALTER TABLE [dbo].[TD_THEME] ADD  CONSTRAINT [THM_CODE_SEQUENCE]  DEFAULT (NEXT VALUE FOR [dbo].[THM_CODE_seq]) FOR [THM_CODE]
GO

ALTER TABLE TD_SUBJECT ADD  SBJ_THM_ID INT NOT NULL CONSTRAINT THM_TEMP_CONSTRAINT DEFAULT(1) WITH VALUES
ALTER TABLE TD_SUBJECT DROP CONSTRAINT THM_TEMP_CONSTRAINT

CREATE TABLE [dbo].[TD_THEME_LANGUAGE](
	[TLG_ID] [int] IDENTITY(1,1) NOT NULL,
	[TLG_VALUE] [nvarchar](256) NOT NULL,
	[TLG_LNG_ID] [int] NOT NULL,
	[TLG_THM_ID] [int] NOT NULL,
 CONSTRAINT [PK_TD_THEME_LANGUAGE] PRIMARY KEY CLUSTERED 
(
	[TLG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER table TD_VARIABLE ADD VRB_ELIMINATION_FLAG BIT NOT NULL DEFAULT(0)
GO

-- alter Data

INSERT INTO TD_THEME (THM_VALUE,THM_LNG_ID,THM_DTG_ID,THM_DELETE_FLAG)
VALUES ('Other',1,1,0)
GO


-- alter Indexes
CREATE NONCLUSTERED INDEX [IX_THM_CODE] ON [dbo].[TD_THEME]
(
	[THM_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_THM_LNG_ID] ON [dbo].[TD_THEME]
(
	[THM_LNG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_THM_DTG_ID] ON [dbo].[TD_THEME]
(
	[THM_DTG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_THM_DELETE_FLAG] ON [dbo].[TD_THEME]
(
	[THM_DELETE_FLAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_SBJ_THM_ID] ON [dbo].[TD_SUBJECT]
(
	[SBJ_THM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_TLG_LNG_ID] ON [dbo].[TD_THEME_LANGUAGE]
(
	[TLG_LNG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TLG_THM_ID] ON [dbo].[TD_THEME_LANGUAGE]
(
	[TLG_THM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_VRB_ELIMINATION_FLAG] ON [dbo].[TD_VARIABLE]
(
	[VRB_ELIMINATION_FLAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

-- alter Constraints
ALTER TABLE [dbo].[TD_THEME]  WITH CHECK ADD  CONSTRAINT [FK_TD_THEME_TS_LANGUAGE] FOREIGN KEY([THM_LNG_ID])
REFERENCES [dbo].[TS_LANGUAGE] ([LNG_ID])
GO
ALTER TABLE [dbo].[TD_THEME]  WITH CHECK ADD  CONSTRAINT [FK_TD_THEME_TD_AUDITING] FOREIGN KEY([THM_DTG_ID])
REFERENCES [dbo].[TD_AUDITING] ([DTG_ID])
GO
ALTER TABLE [dbo].[TD_THEME] ADD  CONSTRAINT [DF_TD_THEME_THM_DELETE_FLAG]  DEFAULT ((0)) FOR [THM_DELETE_FLAG]
GO

ALTER TABLE [dbo].[TD_SUBJECT]  WITH NOCHECK ADD  CONSTRAINT [FK_TD_SUBJECT_TD_THEME] FOREIGN KEY([SBJ_THM_ID])
REFERENCES [dbo].[TD_THEME] ([THM_ID])
GO
ALTER TABLE [dbo].[TD_SUBJECT] CHECK CONSTRAINT [FK_TD_SUBJECT_TD_THEME]
GO

ALTER TABLE [dbo].[TD_THEME_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_TD_THEME_LANGUAGE_TD_THEME] FOREIGN KEY([TLG_THM_ID])
REFERENCES [dbo].[TD_THEME] ([THM_ID])
GO
ALTER TABLE [dbo].[TD_THEME_LANGUAGE] CHECK CONSTRAINT [FK_TD_THEME_LANGUAGE_TD_THEME]
GO
ALTER TABLE [dbo].[TD_THEME_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_TD_THEME_LANGUAGE_TS_LANGUAGE] FOREIGN KEY([TLG_LNG_ID])
REFERENCES [dbo].[TS_LANGUAGE] ([LNG_ID])
GO
ALTER TABLE [dbo].[TD_THEME_LANGUAGE] CHECK CONSTRAINT [FK_TD_THEME_LANGUAGE_TS_LANGUAGE]
GO








