
-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies

-- drop Views and dependencies

-- drop Types and dependencies

-- alter database structure

--Create GEOMAP tables and indexes

CREATE TABLE TD_GEOLAYER
(
	GLR_ID INT IDENTITY(1,1) NOT NULL,
	GLR_NAME NVARCHAR(256) NOT NULL,
	GLR_CODE NVARCHAR(256) NOT NULL,
	GLR_DTG_ID INT NOT NULL,
	GLR_DELETE_FLAG BIT NOT NULL
 CONSTRAINT [PK_TD_GEOLAYER] PRIMARY KEY CLUSTERED 
(
	[GLR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TD_GEOLAYER] ADD  CONSTRAINT [DF_TD_GEOLAYER_DELETE_FLAG]  DEFAULT ((0)) FOR [GLR_DELETE_FLAG]
GO

ALTER TABLE [dbo].[TD_GEOLAYER]  WITH CHECK ADD  CONSTRAINT [FK_TD_GEOLAYER_TD_AUDITING] FOREIGN KEY([GLR_DTG_ID])
REFERENCES [dbo].[TD_AUDITING] ([DTG_ID])
GO

ALTER TABLE [dbo].[TD_GEOLAYER] CHECK CONSTRAINT [FK_TD_GEOLAYER_TD_AUDITING]
GO

CREATE NONCLUSTERED INDEX [IX_GLR_NAME] ON [dbo].[TD_GEOLAYER]
(
	[GLR_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GLR_CODE] ON [dbo].[TD_GEOLAYER]
(
	[GLR_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GLR_DTG_ID] ON [dbo].[TD_GEOLAYER]
(
	[GLR_DTG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GLR_DELETE_FLAG] ON [dbo].[TD_GEOLAYER]
(
	[GLR_DELETE_FLAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



CREATE TABLE TD_GEOMAP
(
	GMP_ID INT IDENTITY(1,1) NOT NULL,
	GMP_CODE NVARCHAR(32) NOT NULL,
	GMP_NAME NVARCHAR(256) NOT NULL,
	GMP_DESCRIPTION NVARCHAR(512) NOT NULL,
	GMP_GEOJSON NVARCHAR(MAX) NOT NULL,
	GMP_FEATURE_COUNT INT NOT NULL,
	GMP_GLR_ID INT NOT NULL,
	GMP_DTG_ID INT NOT NULL,
	GMP_DELETE_FLAG BIT NOT NULL
 CONSTRAINT [PK_TD_GEOMAP] PRIMARY KEY CLUSTERED 
(
	[GMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TD_GEOMAP] ADD  CONSTRAINT [DF_TD_GEOMAP_GMP_DELETE_FLAG]  DEFAULT ((0)) FOR [GMP_DELETE_FLAG]
GO

ALTER TABLE [dbo].[TD_GEOMAP] ADD  CONSTRAINT [DF_TD_GEOMAP_GMP_FEATURE_COUNT]  DEFAULT ((0)) FOR [GMP_FEATURE_COUNT]
GO

ALTER TABLE [dbo].[TD_GEOMAP]  WITH CHECK ADD  CONSTRAINT [FK_TD_GEOMAP_TD_GEOLAYER] FOREIGN KEY([GMP_GLR_ID])
REFERENCES [dbo].[TD_GEOLAYER] ([GLR_ID])
GO

ALTER TABLE [dbo].[TD_GEOMAP] CHECK CONSTRAINT [FK_TD_GEOMAP_TD_GEOLAYER]
GO

ALTER TABLE [dbo].[TD_GEOMAP]  WITH CHECK ADD  CONSTRAINT [FK_TD_GEOMAP_TD_AUDITING] FOREIGN KEY([GMP_DTG_ID])
REFERENCES [dbo].[TD_AUDITING] ([DTG_ID])
GO

ALTER TABLE [dbo].[TD_GEOMAP] CHECK CONSTRAINT [FK_TD_GEOMAP_TD_AUDITING]
GO




CREATE NONCLUSTERED INDEX [IX_GMP_CODE] ON [dbo].[TD_GEOMAP]
(
	[GMP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



CREATE NONCLUSTERED INDEX [IX_GMP_GLR_ID] ON [dbo].[TD_GEOMAP]
(
	[GMP_GLR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GMP_DTG_ID] ON [dbo].[TD_GEOMAP]
(
	[GMP_DTG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GMP_DELETE_FLAG] ON [dbo].[TD_GEOMAP]
(
	[GMP_DELETE_FLAG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

--Remove unnecessary column on TM_DATA_CELL  [ENHANCEMENT] Remove column DTC_ID from table TM_DATA_CELL #434

ALTER TABLE TM_DATA_CELL DROP CONSTRAINT IF EXISTS PK_TM_DATA_CELL
GO

ALTER TABLE TM_DATA_CELL DROP COLUMN IF EXISTS DTC_ID
GO



-- alter database data 