ALTER TABLE TD_MATRIX
ADD MTR_MIGRATION_FLAG BIT NULL

CREATE TABLE TD_MATRIX_DATA
(
	MTD_ID INT IDENTITY(1,1) NOT NULL,
	MTD_MTR_ID INT NOT NULL,
	MTD_DATA NVARCHAR(MAX),
	[MTD_DECIMAL] [tinyint] NOT NULL,
 CONSTRAINT [PK_TD_MATRIX_DATA] PRIMARY KEY CLUSTERED 
(
	[MTD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TD_MATRIX_DATA] ADD  CONSTRAINT [DF_TD_MATRIX_DATA_MTD_DECIMAL]  DEFAULT ((0)) FOR [MTD_DECIMAL]
GO

ALTER TABLE [dbo].[TD_MATRIX_DATA]  WITH CHECK ADD  CONSTRAINT [FK_TD_MATRIX_DATA_TD_MATRIX] FOREIGN KEY([MTD_MTR_ID])
REFERENCES [dbo].[TD_MATRIX] ([MTR_ID])
GO

ALTER TABLE [dbo].[TD_MATRIX_DATA] CHECK CONSTRAINT [FK_TD_MATRIX_DATA_TD_MATRIX]
GO

CREATE NONCLUSTERED INDEX [IX_MTD_MTR_ID] ON [dbo].[TD_MATRIX_DATA]
(
	[MTD_MTR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE TS_DIMENSION_ROLE
(
	DMR_ID INT IDENTITY(1,1) NOT NULL,
	DMR_CODE NVARCHAR(128) NOT NULL,
	DMR_VALUE NVARCHAR(512) NOT NULL
,
 CONSTRAINT [PK_TD_DIMENSION_ROLE] PRIMARY KEY CLUSTERED 
(
	[DMR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_DMR_CODE] ON [dbo].[TS_DIMENSION_ROLE]
(
	[DMR_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE TD_MATRIX_DIMENSION
(
	MDM_ID INT IDENTITY(1,1) NOT NULL,
	MDM_SEQUENCE INT NOT NULL,
	MDM_CODE NVARCHAR(256),
	MDM_VALUE NVARCHAR(256),
	MDM_MTR_ID INT,
	MDM_DMR_ID INT,
	MDM_GEO_FLAG BIT,
	MDM_GEO_URL NVARCHAR(2048),
 CONSTRAINT [PK_TD_MATRIX_DIMENSION] PRIMARY KEY CLUSTERED 
(
	[MDM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TD_MATRIX_DIMENSION]  WITH CHECK ADD  CONSTRAINT [FK_TD_MATRIX_DIMENSION_TD_MATRIX] FOREIGN KEY([MDM_MTR_ID])
REFERENCES [dbo].[TD_MATRIX] ([MTR_ID])
GO

ALTER TABLE [dbo].[TD_MATRIX_DIMENSION] CHECK CONSTRAINT [FK_TD_MATRIX_DIMENSION_TD_MATRIX]
GO

ALTER TABLE [dbo].[TD_MATRIX_DIMENSION]  WITH CHECK ADD  CONSTRAINT [FK_TD_MATRIX_DIMENSION_TS_DIMENSION_ROLE] FOREIGN KEY([MDM_DMR_ID])
REFERENCES [dbo].[TS_DIMENSION_ROLE] ([DMR_ID])
GO

ALTER TABLE [dbo].[TD_MATRIX_DIMENSION] CHECK CONSTRAINT [FK_TD_MATRIX_DIMENSION_TS_DIMENSION_ROLE]
GO

ALTER TABLE [dbo].[TD_MATRIX_DIMENSION] ADD  CONSTRAINT [DF_TD_MATRIX_DIMENSION_MDM_GEO_FLAG]  DEFAULT ((0)) FOR [MDM_GEO_FLAG]
GO




CREATE NONCLUSTERED INDEX [IX_MDM_CODE] ON [dbo].[TD_MATRIX_DIMENSION]
(
	[MDM_MTR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_MDM_MTR_ID_SEQUENCE] ON [dbo].[TD_MATRIX_DIMENSION]
(
	[MDM_MTR_ID] ASC,
	[MDM_SEQUENCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_MDM_MTR_ID] ON [dbo].[TD_MATRIX_DIMENSION]
(
	[MDM_MTR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TD_DIMENSION_ITEM](
	[DMT_ID] [int] IDENTITY(1,1) NOT NULL,
	[DMT_CODE] [nvarchar](256) NULL,
	[DMT_VALUE] [nvarchar](256) NULL,
	[DMT_SEQUENCE] [int] NOT NULL,
	[DMT_MDM_ID] [int] NOT NULL,
	[DMT_ELIMINATION_FLAG] [bit] NOT NULL,
	[DMT_DECIMAL] [tinyint] NOT NULL,
	[DMT_UNIT] [nvarchar](256) NULL,
	 
 CONSTRAINT [PK_TD_DIMENSION_ITEM] PRIMARY KEY CLUSTERED 
(
	[DMT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TD_DIMENSION_ITEM] ADD  CONSTRAINT [DF_TD_DIMENSION_ITEM_DMT_ELIMINATION_FLAG]  DEFAULT ((0)) FOR [DMT_ELIMINATION_FLAG]
GO

ALTER TABLE [dbo].[TD_DIMENSION_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_TD_DIMENSION_ITEM_TD_MATRIX_DIMENSION] FOREIGN KEY(DMT_MDM_ID)
REFERENCES [dbo].TD_MATRIX_DIMENSION ([MDM_ID])
GO

ALTER TABLE [dbo].[TD_DIMENSION_ITEM] ADD  CONSTRAINT [DF_TD_DIMENSION_ITEM_DMT_DECIMAL]  DEFAULT ((0)) FOR [DMT_DECIMAL]
GO

ALTER TABLE [dbo].[TD_DIMENSION_ITEM] CHECK CONSTRAINT [FK_TD_DIMENSION_ITEM_TD_MATRIX_DIMENSION]
GO

CREATE NONCLUSTERED INDEX [IX_DMT_SEQUENCE_MDM_ID] ON [dbo].TD_DIMENSION_ITEM
(
	[DMT_MDM_ID] ASC,
	[DMT_SEQUENCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_DMT_MDM_ID] ON [dbo].TD_DIMENSION_ITEM
(
	[DMT_MDM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

INSERT INTO TS_DIMENSION_ROLE 
(DMR_CODE,DMR_VALUE)
VALUES
('STATISTIC','Statistic')

INSERT INTO TS_DIMENSION_ROLE 
(DMR_CODE,DMR_VALUE)
VALUES
('TIME','Time')

INSERT INTO TS_DIMENSION_ROLE 
(DMR_CODE,DMR_VALUE)
VALUES
('CLASSIFICATION','Classification')