
-- drop Jobs and dependencies

-- drop StoredProcedures and dependencies

-- drop Views and dependencies

-- drop Types and dependencies

-- alter database structure
CREATE TABLE TM_RELEASE_PRODUCT
(
	RPR_ID INT IDENTITY(1,1) NOT NULL,
	RPR_RLS_ID INT,
	RPR_PRC_ID INT,
	RPR_DTG_ID INT NOT NULL,
	RPR_DELETE_FLAG BIT NOT NULL
 CONSTRAINT [PK_TM_RELEASE_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[RPR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_RPR_RLS_ID] ON [dbo].[TM_RELEASE_PRODUCT]
(
	[RPR_RLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_RPR_PRC_ID] ON [dbo].[TM_RELEASE_PRODUCT]
(
	[RPR_PRC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_RPR_DTG_ID] ON [dbo].[TM_RELEASE_PRODUCT]
(
	[RPR_DTG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TM_RELEASE_PRODUCT]  WITH CHECK ADD CONSTRAINT [FK_TM_RELEASE_PRODUCT_TD_RELEASE] FOREIGN KEY([RPR_RLS_ID])
REFERENCES [dbo].[TD_RELEASE] ([RLS_ID])
GO

ALTER TABLE [dbo].[TM_RELEASE_PRODUCT] CHECK CONSTRAINT [FK_TM_RELEASE_PRODUCT_TD_RELEASE]
GO

ALTER TABLE [dbo].[TM_RELEASE_PRODUCT]  WITH CHECK ADD CONSTRAINT [FK_TM_RELEASE_PRODUCT_TD_PRODUCT] FOREIGN KEY([RPR_PRC_ID])
REFERENCES [dbo].[TD_PRODUCT] ([PRC_ID])
GO

ALTER TABLE [dbo].[TM_RELEASE_PRODUCT]  WITH CHECK ADD CONSTRAINT [FK_TM_RELEASE_PRODUCT_TD_AUDITING] FOREIGN KEY([RPR_DTG_ID])
REFERENCES [dbo].[TD_AUDITING] ([DTG_ID])
GO

ALTER TABLE [dbo].[TM_RELEASE_PRODUCT] CHECK CONSTRAINT [FK_TM_RELEASE_PRODUCT_TD_RELEASE]
GO
-- alter database data


