
CREATE UNIQUE NONCLUSTERED INDEX [IX_CHN_CODE] ON [dbo].[TS_CHANNEL]
(
	[CHN_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

EXEC sp_rename 'dbo.PK_TS_DOMAIN', 'PK_TS_CHANNEL';
GO

EXEC sp_rename 'dbo.PK_TD_DOMAIN_SUBSCRIPTION', 'PK_TM_CHANNEL_SUBSCRIPTION';
GO

EXEC sp_rename 'dbo.FK_TD_CHANNEL_SUBSCRIPTION_TD_USER', 'FK_TM_CHANNEL_SUBSCRIPTION_TD_USER';
GO

EXEC sp_rename 'dbo.TM_CHANNEL_SUBSCRIPTION.IX_DSB_DMN_ID', 'IX_CSB_CHN_ID', 'INDEX';
GO

ALTER TABLE TD_DIMENSION_ITEM ALTER COLUMN DMT_CODE NVARCHAR (256) NOT NULL;
GO

ALTER TABLE TD_DIMENSION_ITEM ALTER COLUMN DMT_VALUE NVARCHAR (256) NOT NULL;
GO

ALTER TABLE [dbo].[TS_CHANNEL_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_TS_CHANNEL_LANGUAGE_TS_CHANNEL] FOREIGN KEY([CHL_CHN_ID])
REFERENCES [dbo].[TS_CHANNEL] ([CHN_ID])
GO

ALTER TABLE [dbo].[TS_CHANNEL_LANGUAGE] CHECK CONSTRAINT [FK_TS_CHANNEL_LANGUAGE_TS_CHANNEL]
GO


