if(SELECT count(*)
FROM sys.indexes 
WHERE name='IX_TRC_METHOD' AND object_id = OBJECT_ID('[dbo].[TD_TRACE]'))=0
BEGIN

CREATE NONCLUSTERED INDEX [IX_TRC_METHOD] ON [dbo].[TD_TRACE]
(
	[TRC_METHOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO

if(SELECT count(*)
FROM sys.indexes 
WHERE name='IX_TRC_DATETIME' AND object_id = OBJECT_ID('[dbo].[TD_TRACE]'))=0
BEGIN

CREATE NONCLUSTERED INDEX [IX_TRC_DATETIME] ON [dbo].[TD_TRACE]
(
	[TRC_DATETIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO