


IF (SELECT count(*) FROM sys.columns 
          WHERE Name = N'CCN_API_TOKEN'
          AND Object_ID = Object_ID(N'dbo.TD_ACCOUNT'))=0
BEGIN
   ALTER TABLE TD_ACCOUNT
	ADD CCN_API_TOKEN NVARCHAR(256) NULL
END
GO




if(SELECT count(*)
FROM sys.indexes 
WHERE name='IX_CCN_API_TOKEN' AND object_id = OBJECT_ID('[dbo].[TD_ACCOUNT]'))=0
BEGIN
CREATE NONCLUSTERED INDEX [IX_CCN_API_TOKEN] ON [dbo].TD_ACCOUNT
(
	[CCN_API_TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO



