SET QUOTED_IDENTIFIER ON
GO
-- This is used only for migration
CREATE
	OR

ALTER PROCEDURE [dbo].[Api_Settings_Update] @apiversion DECIMAL(10, 2)
	,@apikey VARCHAR(200)
	,@apikeyNew VARCHAR(200) = NULL
	,@apivalue VARCHAR(MAX) = NULL
	,@apidescription VARCHAR(MAX) = NULL
	,@apisensitivevalue BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @APIASVID AS INT;

	SET @APIASVID = (
			SELECT TM_APP_SETTING_CONFIG_VERSION.ASV_ID
			FROM TM_APP_SETTING_CONFIG_VERSION
			INNER JOIN TS_CONFIG_SETTING_TYPE ON TS_CONFIG_SETTING_TYPE.CST_ID = TM_APP_SETTING_CONFIG_VERSION.ASV_CST_ID
			WHERE (TS_CONFIG_SETTING_TYPE.CST_CODE = 'API')
				AND TM_APP_SETTING_CONFIG_VERSION.ASV_VERSION = @apiversion
			);

	UPDATE TS_API_SETTING
	SET API_KEY = COALESCE(@apikeyNew, API_KEY)
		,API_VALUE = COALESCE(@apivalue, API_VALUE)
		,API_DESCRIPTION = COALESCE(@apidescription, API_DESCRIPTION)
		,API_SENSITIVE_VALUE = COALESCE(@apisensitivevalue, API_SENSITIVE_VALUE)
	WHERE API_ASV_ID = @APIASVID
		AND API_KEY = @apikey
END