UPDATE TD_MATRIX
SET MTR_MIGRATION_FLAG=NULL

DELETE FROM TD_MATRIX_DATA 
WHERE MTD_MTR_ID IN
(
SELECT MTR_ID
FROM TD_MATRIX
WHERE MTR_MIGRATION_FLAG IS NULL OR MTR_MIGRATION_FLAG=0

)

DELETE FROM TD_DIMENSION_ITEM 
WHERE DMT_MDM_ID IN
(
SELECT MDM_ID FROM TD_MATRIX_DIMENSION 
INNER JOIN TD_MATRIX
ON MDM_MTR_ID =MTR_ID
AND (MTR_MIGRATION_FLAG IS NULL OR MTR_MIGRATION_FLAG=0)
)

DELETE FROM TD_MATRIX_DIMENSION 
WHERE MDM_ID IN
(
SELECT MDM_ID FROM TD_MATRIX_DIMENSION 
INNER JOIN TD_MATRIX
ON MDM_MTR_ID =MTR_ID

AND (MTR_MIGRATION_FLAG IS NULL OR MTR_MIGRATION_FLAG=0))

--select count(*) from TD_MATRIX where MTR_DELETE_FLAG=0 and MTR_MIGRATION_FLAG=1