/****** Object:  StoredProcedure [dbo].[Subscription_Query_Read]    Script Date: 07/02/2022 11:52:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER
	

 PROCEDURE [dbo].[Subscription_Query_Read] @UserQueryId NVARCHAR(256)
	,@SubscriberUserId NVARCHAR(256) = NULL
	,@CcnUsername NVARCHAR(256) = NULL
AS
BEGIN
	SET NOCOUNT ON;
	IF @SubscriberUserId IS NULL
		AND @CcnUsername IS NULL
	BEGIN
		RETURN 0;
	END

	DECLARE @UserId AS INT;

	IF @SubscriberUserId IS NOT NULL
	BEGIN
		SET @UserId = (
				SELECT USR_ID
				FROM TD_USER
				INNER JOIN TD_SUBSCRIBER ON SBR_USR_ID = USR_ID
					AND SBR_UID = @SubscriberUserId
					AND SBR_DELETE_FLAG = 0
				);
	END
	ELSE
	BEGIN
		SET @UserId = (
				SELECT USR_ID
				FROM TD_USER
				INNER JOIN TD_ACCOUNT ON CCN_USR_ID = USR_ID
					AND CCN_USERNAME = @CcnUsername
					AND CCN_DELETE_FLAG = 0
				);
	END

	IF @UserId IS NULL
	BEGIN
		RETURN 0;
	END

	SELECT SQR_ID AS Id
		,SQR_SNIPPET_TAGNAME AS TagName
		,SQR_SNIPPET_MATRIX AS Matrix
		,SQR_SNIPPET_TYPE AS SnippetType
		,CAST(decompress(SQR_SNIPPET_QUERY) AS NVARCHAR(MAX)) AS SnippetQueryBase64
		,SQR_FLUID_TIME AS FluidTime
		,SQR_SNIPPET_ISOGRAM AS SnippetIsogram
	FROM TD_USER_QUERY
	WHERE SQR_USR_ID = @UserId
	AND SQR_ID = @UserQueryId
END

SET ANSI_NULLS ON;