//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PxStat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PxStat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ { } ].
        /// </summary>
        internal static string dictionary_en {
            get {
                return ResourceManager.GetString("dictionary_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;abacais&quot;:&quot;abacas&quot;,&quot;abacas&quot;:&quot;abacas&quot;,&quot;abacht&quot;:&quot;abacht&quot;,&quot;abachta&quot;:&quot;abacht&quot;,&quot;abach&quot;:&quot;abach&quot;,&quot;abaigh&quot;:&quot;abach&quot;,&quot;abairtí&quot;:&quot;abairt&quot;,&quot;abairte&quot;:&quot;abairt&quot;,&quot;abarlacha&quot;:&quot;abarlach&quot;,&quot;abarlaí&quot;:&quot;abarlach&quot;,&quot;abarlach&quot;:&quot;abarlach&quot;,&quot;abarthacht&quot;:&quot;abarthacht&quot;,&quot;abarthachta&quot;:&quot;abarthacht&quot;,&quot;abair&quot;:&quot;abar&quot;,&quot;abar&quot;:&quot;abar&quot;,&quot;abdómain&quot;:&quot;abdóman&quot;,&quot;abdóman&quot;:&quot;abdóman&quot;,&quot;abhacréaltaí&quot;:&quot;abhacréalta&quot;,&quot;abhacréalta&quot;:&quot;abhacréalta&quot;,&quot;abhaic&quot;:&quot;abhac&quot;,&quot;abhac&quot;:&quot;abhac&quot;,&quot;abhacáid&quot;:&quot;abhacád&quot;,&quot;abhacád&quot;:&quot;abhacád&quot;,&quot;abhlacha&quot;:&quot;abhaill&quot;,&quot;abhla&quot;:&quot;abhaill&quot;,&quot;aibhne [re....
        /// </summary>
        internal static string dictionary_ga {
            get {
                return ResourceManager.GetString("dictionary_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Release&quot;,
        ///    &quot;all-groups&quot;: &quot;All Groups&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Invalid authentication. Access denied.&quot;,
        ///    &quot;create&quot;: &quot;No record has been created. Please review your input.&quot;,
        ///    &quot;delete&quot;: &quot;No record has been deleted. Please review your selection.&quot;,
        ///    &quot;duplicate&quot;: &quot;No record has been created. A duplicate record already exists. Please review your input.&quot;,
        ///    &quot;exception&quot;: &quot;An unexpected error has occurred. Please seek technical support.&quot;,
        ///    &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Scaoileadh &quot;,
        ///    &quot;all-groups&quot;: &quot;Gach grúpa&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Fíordheimhniú neamhbhailí. Ní cheadaítear rochtain&quot;,
        ///    &quot;create&quot;: &quot;Níor cruthaíodh aon taifead. Déan athbhreithniú ar d’ionchur le do thoil.&quot;,
        ///    &quot;delete&quot;: &quot;Níor scriosadh aon taifead. Déan athbhreithniú ar do rogha le do thoil.&quot;,
        ///    &quot;duplicate&quot;: &quot;Níor cruthaíodh aon taifead. Tá taifead dúblach ann cheana féin. Déan athbhreithniú ar d’ionchur le do thoil.&quot;,
        ///    &quot;exception&quot;: &quot;Tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ga {
            get {
                return ResourceManager.GetString("ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;excluded&quot;: {
        ///    &quot;article&quot;: [ &quot;the&quot;, &quot;an&quot;, &quot;a&quot; ],
        ///    &quot;preposition&quot;: [ &quot;of&quot;, &quot;in&quot;, &quot;to&quot;, &quot;for&quot;, &quot;with&quot;, &quot;on&quot;, &quot;at&quot;, &quot;from&quot;, &quot;by&quot;, &quot;about&quot;, &quot;as&quot;, &quot;into&quot;, &quot;like&quot;, &quot;through&quot;, &quot;after&quot;, &quot;over&quot;, &quot;between&quot;, &quot;out&quot;, &quot;against&quot;, &quot;during&quot;, &quot;without&quot;, &quot;before&quot;, &quot;under&quot;, &quot;around&quot;, &quot;among&quot;, &quot;and&quot;, &quot;or&quot; ],
        ///    &quot;interrogative&quot;: [ &quot;how&quot;, &quot;where&quot;, &quot;what&quot;, &quot;why&quot;, &quot;when&quot;, &quot;who&quot;, &quot;which&quot;, &quot;much&quot;, &quot;many&quot; ],
        ///    &quot;miscellaneous&quot;: [ &quot;has&quot;, &quot;have&quot;, &quot;is&quot;, &quot;are&quot;, &quot;not&quot; ],
        ///    &quot;regex&quot;: &quot;[^a-zA-Z\\d\\s:]&quot;
        ///  },
        ///  &quot;infle....
        /// </summary>
        internal static string keyword_en {
            get {
                return ResourceManager.GetString("keyword_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;excluded&quot;: {
        ///    &quot;article&quot;: [ &quot;na&quot;, &quot;an&quot; ],
        ///    &quot;preposition&quot;: [ &quot;agus&quot;, &quot;ag&quot;, &quot;ar&quot;, &quot;as&quot;, &quot;chun&quot;, &quot;chuig&quot;, &quot;de&quot;, &quot;do&quot;, &quot;den&quot;, &quot;don&quot;, &quot;fara&quot;, &quot;faoi&quot;, &quot;i&quot;, &quot;in&quot;, &quot;idir&quot;, &quot;ionsar&quot;, &quot;le&quot;, &quot;ó&quot;, &quot;roimh&quot;, &quot;trí&quot;, &quot;thar&quot;, &quot;um&quot;, &quot;a&quot;, &quot;dar&quot;, &quot;is&quot;, &quot;gan&quot;, &quot;go&quot;, &quot;godtí&quot;, &quot;go dtí&quot;, &quot;mar&quot;, &quot;os&quot;, &quot;seachas&quot; ],
        ///    &quot;interrogative&quot;: [ &quot;cé&quot;, &quot;cén&quot;, &quot;cá&quot;, &quot;cad&quot;, &quot;conas&quot;, &quot;cathain&quot;, &quot;bhfuil&quot;, &quot;nach&quot;, &quot;nár&quot;, &quot;ar&quot;, &quot;air&quot; ],
        ///    &quot;miscellaneous&quot;: [ &quot;méid&quot;, &quot;mhéid&quot;, &quot;faoin&quot;, &quot;is&quot;, &quot;céi....
        /// </summary>
        internal static string keyword_ga {
            get {
                return ResourceManager.GetString("keyword_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;static&quot;: [ &quot;january, february, march, april, may, june, july, august, september, october, november, december, cpi, annual, average,total,mean,median,hourly,weekly,daily,monthly&quot; ],
        ///    &quot;excluded&quot;: {
        ///        &quot;article&quot;: [ &quot;the,an,a&quot; ],
        ///        &quot;preposition&quot;: [ &quot;of, in, to, for, with, on, at, from, by, about, as, into, like, through, after, over, between, out, against, during, without, before, under, around, among, and, or&quot; ],
        ///        &quot;interrogative&quot;: [ &quot;how&quot;, &quot;where&quot;, &quot;what&quot;, &quot;why&quot;, &quot;when&quot;, &quot;who&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keyword_pl {
            get {
                return ResourceManager.GetString("keyword_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Wydanie&quot;,
        ///    &quot;all-groups&quot;: &quot;Wszystkie Grupy&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Niepoprawne uwierzytelnienie. Brak dostępu.&quot;,
        ///    &quot;create&quot;: &quot;Nie utworzono żadnego rekordu. Sprawdź swoje dane wejściowe.&quot;,
        ///    &quot;delete&quot;: &quot;Żaden rekord nie został usunięty. Sprawdź swój wybór.&quot;,
        ///    &quot;duplicate&quot;: &quot;Nie utworzono żadnego rekordu. Zduplikowany rekord już istnieje. Sprawdź swoje dane wejściowe.&quot;,
        ///    &quot;exception&quot;: &quot;Wystąpił nieoczekiwany błąd. Proszimy o kontakt z pomoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;match&quot;:&quot;mutilate&quot;,&quot;lemma&quot;:&quot;mutilation&quot;},{&quot;match&quot;:&quot;prank&quot;,&quot;lemma&quot;:&quot;prankster&quot;},{&quot;match&quot;:&quot;hope&quot;,&quot;lemma&quot;:&quot;despair&quot;},{&quot;match&quot;:&quot;ascetically&quot;,&quot;lemma&quot;:&quot;ascetic&quot;},{&quot;match&quot;:&quot;withdraw&quot;,&quot;lemma&quot;:&quot;withdrawer&quot;},{&quot;match&quot;:&quot;Jamaican&quot;,&quot;lemma&quot;:&quot;Jamaica&quot;},{&quot;match&quot;:&quot;ionize&quot;,&quot;lemma&quot;:&quot;ionization&quot;},{&quot;match&quot;:&quot;susceptible&quot;,&quot;lemma&quot;:&quot;susceptibleness&quot;},{&quot;match&quot;:&quot;sorriness&quot;,&quot;lemma&quot;:&quot;sorry&quot;},{&quot;match&quot;:&quot;ascertain&quot;,&quot;lemma&quot;:&quot;ascertainable&quot;},{&quot;match&quot;:&quot;express&quot;,&quot;lemma&quot;:&quot;local&quot;},{&quot;match&quot;:&quot;punt&quot;,&quot;lemma&quot;:&quot;punter&quot;},{&quot;match&quot;:&quot;evade&quot;,&quot;lemma&quot;:&qu....
        /// </summary>
        internal static string synonym_en {
            get {
                return ResourceManager.GetString("synonym_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;match&quot;:&quot;ab&quot;,&quot;lemma&quot;:&quot;ab&quot;},{&quot;match&quot;:&quot;abacas&quot;,&quot;lemma&quot;:&quot;abacas&quot;},{&quot;match&quot;:&quot;abacht&quot;,&quot;lemma&quot;:&quot;abacht&quot;},{&quot;match&quot;:&quot;abairt&quot;,&quot;lemma&quot;:&quot;abairt&quot;},{&quot;match&quot;:&quot;abairtín&quot;,&quot;lemma&quot;:&quot;abairt&quot;},{&quot;match&quot;:&quot;frása&quot;,&quot;lemma&quot;:&quot;abairt&quot;},{&quot;match&quot;:&quot;abairt&quot;,&quot;lemma&quot;:&quot;abairtín&quot;},{&quot;match&quot;:&quot;abairtín&quot;,&quot;lemma&quot;:&quot;abairtín&quot;},{&quot;match&quot;:&quot;frása&quot;,&quot;lemma&quot;:&quot;abairtín&quot;},{&quot;match&quot;:&quot;ábaltacht&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:&quot;acmhainn&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:&quot;bua&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:&quot;cumas&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:....
        /// </summary>
        internal static string synonym_ga {
            get {
                return ResourceManager.GetString("synonym_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-16&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;background-color: #fff; font-family: &apos;Roboto Sans&apos;, sans-serif; color: #384350; font-size: 15px; padding: 0 0 0 0;&quot;&gt;
        ///
        ///    &lt;div class=&quot;container&quot; style=&quot;margin: 0px auto;  width: 75%;&quot;&gt;
        ///        &lt;h1&gt;{title}&lt;/h1&gt;
        ///        &lt;h2&gt;{subject}&lt;/h2&gt;
        ///        &lt;hr&gt;
        ///
        ///        &lt;p&gt;{body}&lt;/p&gt;
        ///
        ///        &lt;hr&gt;
        ///        &lt;p style=&quot;font-size: smaller;&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_GroupMessage {
            get {
                return ResourceManager.GetString("template_GroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-16&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;background-color: #fff; font-family: &apos;Roboto Sans&apos;, sans-serif; color: #384350; font-size: 15px; padding: 0 0 0 0;&quot;&gt;
        ///
        ///    &lt;div class=&quot;container&quot; style=&quot;margin: 0px auto;  width: 75%;&quot;&gt;
        ///        &lt;h1&gt;{title}&lt;/h1&gt;
        ///        &lt;h2&gt;{subject}&lt;/h2&gt;
        ///        &lt;hr&gt;
        ///
        ///        &lt;p&gt;{body}&lt;/p&gt;
        ///
        ///        &lt;hr&gt;
        ///        &lt;p style=&quot;font-size: smaller;&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_NotifyWorkflow {
            get {
                return ResourceManager.GetString("template_NotifyWorkflow", resourceCulture);
            }
        }
    }
}
